### PR TITLE
Fixed issue #1 : Need to add NSFW reporting to tracks

### PR DESCRIPTION
**Pull request by ymauray**
For each track for which `isNSFW` is not set, a button will appear to "Report this track as not safe for family or work".
Pushing this button will set the `needsReview` flag for that track, and replace the report button with a message : "This track has been reported as not safe for family or work, it will be reviewed by a moderator."
Site admins also see a message asking "Is this track safe for family or work ?", with two options, "yes" and "no" (checked by default), and a button to "Review the track".
Pressing that button clears the `needsReview` flag and sets or clears the `isNSFW` flag depending on the admin's choice.

**CAUTION** : prior to (or just after) merging this pull request, the following SQL patch needs to be applied :
```sql
ALTER TABLE `tracks` 
ADD `needsReview` TINYINT(1) NOT NULL DEFAULT '0' AFTER `isNSFW`, 
ADD INDEX `idx_needsReview` (`needsReview`);
```

**NOTE** : A cron job will need to be set to send an email to admins to remind them of the pending reviews.

### CODE REVIEW

**Comment by thelovebug** [comment]
I'm happy to add the SQL column, but I would prefer to leave the merge to @JonTheNiceGuy, as this was his original issue.

Also, I wouldn't recommend an index on a field with only 3 possible discrete values. :-)

**Comment by ymauray** [comment]
Do as you see fit, you are the database expert 😜

**Comment by JonTheNiceGuy** [comment]
I agree. I'm happy with going ahead with this. @TheLoveBug can you make the
DB change and then merge the change once it's done so we don't have a
period where the db is out of sync with the code?

**Comment by thelovebug** [comment]
Database change made as follows:

```SQL
ALTER TABLE `tracks` 
ADD `needsReview` TINYINT(1) NOT NULL DEFAULT '0' AFTER `isNSFW`
```

**Pull request merged**
